#!/usr/bin/env bash
# Creates .env.production for floxtodon.dev on the server, generating every
# secret locally on the machine. Run once as the app user:
#   sudo -u mastodon bash /home/mastodon/live/deploy/configure.sh
# Re-running is safe: an existing .env.production is never overwritten.
#
# Two values are left for the operator to fill in by hand afterwards:
#   SMTP_LOGIN / SMTP_PASSWORD  (Mailjet API key / secret key)
# and the bucket credentials are appended by the HMAC step in deploy/README.md.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env.production"
DOMAIN="${DOMAIN:-floxtodon.dev}"
BUCKET="${BUCKET:-floxtodon-media}"

if [ -f "$ENV_FILE" ]; then
  echo "$ENV_FILE already exists — leaving it untouched."
  exit 0
fi

rand_alnum() { openssl rand -base64 64 | tr -dc 'A-Za-z0-9' | head -c "$1"; }

umask 077
cat > "$ENV_FILE" <<EOF
# Generated by deploy/configure.sh — secrets for floxtodon.dev. Never commit this file.
LOCAL_DOMAIN=$DOMAIN
SINGLE_USER_MODE=false

SECRET_KEY_BASE=$(openssl rand -hex 64)
ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY=$(rand_alnum 32)
ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT=$(rand_alnum 32)
ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY=$(rand_alnum 32)

# Email — Mailjet SMTP relay. Fill in SMTP_LOGIN (API key) and SMTP_PASSWORD (secret key).
SMTP_SERVER=in-v3.mailjet.com
SMTP_PORT=587
SMTP_LOGIN=
SMTP_PASSWORD=
SMTP_FROM_ADDRESS=notifications@$DOMAIN
SMTP_AUTH_METHOD=plain
SMTP_ENABLE_STARTTLS=always

# Media — Google Cloud Storage through its S3-compatible XML API.
# Uniform bucket-level access: no per-object ACLs (S3_PERMISSION empty).
S3_ENABLED=true
S3_BUCKET=$BUCKET
S3_ENDPOINT=https://storage.googleapis.com
S3_HOSTNAME=storage.googleapis.com
S3_REGION=us-west1
S3_PERMISSION=
EOF

echo "== generating VAPID keys (web push)"
cd "$ROOT"
flox activate -d "$ROOT/deploy/server" -c 'bundle exec rails mastodon:webpush:generate_vapid_key' \
  | grep '^VAPID_' >> "$ENV_FILE"

echo "Wrote $ENV_FILE (mode 600). Remaining: SMTP_LOGIN / SMTP_PASSWORD and bucket keys."
